name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: zip file
      run: zip -r hous.zip . -x '*.git*'

    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./hous.zip s3://greatgreat/deploy/

    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name great-app
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name great-group
        --s3-location bucket=great,bundleType=zip,key=deploy/hous.zip